apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-embedding
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      application: image-embedding
  template:
    metadata:
      labels:
        application: image-embedding
    spec:
      ## 포드 스케줄러 작동
      schedulerName: my-scheduler
      ## 어짜피 포드 스케줄러에서 뉴런코어를 담당다기 때문에 따로 노드를 셀렉트 안해줘도 된다
      # nodeSelector:
      #   eks.amazonaws.com/nodegroup: inf_node_group
      containers:
      - name: image-embedding
        image: 916657902198.dkr.ecr.us-east-2.amazonaws.com/image_embed:10
        command:
          - /bin/bash
          - -c
          - |
            ./env/bin/python rabbitmq_emb.py &
            source start.sh
        
        resources:
          limits:
            # cpu: 600m
            # memory: 500Mi
            # aws.amazon.com/neuron: 1
            aws.amazon.com/neuroncore: 1
          # requests:
          #   cpu: 400m
          #   memory: 300Mi
        env:
          - name: redis_host
            value: redis-master.messagesys.svc
          - name: rabbitmq_host
            value: production-rabbitmqcluster.messagesys.svc
---
kind: Service
apiVersion: v1
metadata:
  name: image-embedding
  namespace: application
  labels:
    application: image-embedding
spec:
  selector:
    application: image-embedding
  ports:
  - name: html
    port: 8081
  - name: metrix
    port: 9000
---

## 프로메테우스 메트릭 등록
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-embedding
  namespace: application
  labels:
    release: stack
spec:
  selector:
    matchLabels:
      application: image-embedding
  endpoints:
  - port: metrix