apiVersion: v1
kind: Service
metadata:
  name: prometethus-nodeport
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      name: http
      protocol: TCP
  selector:
     app.kubernetes.io/name: prometheus