apiVersion: v1
kind: Service
metadata:
  name: express-demo
  namespace: demo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
     app: express