# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
#   name: prometheus
#   namespace: argocd
# spec:
#   destination:
#     namespace: monitoring
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     chart: prometheus
#     helm:
#       values: |-
#         alertmanager:
#           persistentVolume:
#             storageClass: gp2
#         server:
#           persistentVolume:
#             storageClass: gp2
#           service:
#             type: LoadBalancer
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 19.3.3
#   syncPolicy:
#     syncOptions:
#     - ServerSideApply=true
#     - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: prometheus-operator
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-operator
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.3.1
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true