apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: stable
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |-
        defaultRules:
          rules:
            etcd: false
            kubeScheduler: false
        kubeControllerManager:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: false
        grafana:
          adminPassword: test123
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
              service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
            type: LoadBalancer
          extraExposePorts:
            - name: https
              port: 443
              targetPort: 3000
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          persistence:
            type: pvc
            enabled: true
            storageClassName: gp2
            accessModes:
              - ReadWriteOnce
            size: 20Gi
        prometheus:
          prometheusSpec:
            retention: 31d
            retentionSize: "20GB"
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 200m
                memory: 256Mi
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: gp2
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 30Gi
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 19.3.0
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true