apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      ## 포드 스케줄러 작동
      schedulerName: my-scheduler
      containers:
      - name: example-app
        image: 916657902198.dkr.ecr.us-east-2.amazonaws.com/temp:1.8
        # image: 763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-inference-neuron:1.12.1-neuron-py38-sdk2.5.0-ubuntu20.04
        # command: command: ["/bin/sleep", "3650d"]
        # command: ["python","myapp.py"]
        # curl http://localhost:9000
        command:
          - /bin/bash
          - -c
          - |
            python myapp.py&
            source start.sh
        
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
            # aws.amazon.com/neuron: 1
            aws.amazon.com/neuroncore: 1
          requests:
            cpu: 400m
            memory: 0.8Gi
---
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: metrix
    port: 9000
  - name: input-api
    port: 8000
---
## 프로메테우스 메트릭 등록
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    release: stack
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: metrix