apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      ## 포드 스케줄러 작동
      # schedulerName: my-scheduler
      containers:
      - name: example-app
        # image: ubuntu:20.04
        image: 916657902198.dkr.ecr.us-east-2.amazonaws.com/temp:0.5
        # command: ["/bin/sleep", "3650d"]
        resources:
          limits:
            cpu: 1
            memory: 2Gi
            # aws.amazon.com/neuron: 1
            aws.amazon.com/neuroncore: 3
          requests:
            cpu: "1"
            memory: 2Gi
---
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: metrix
    port: 9000
  - name: input-api
    port: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    release: stack
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: metrix