apiVersion: v1
kind: Service
metadata:
  name: prometheus-nlb
  namespace: monitoring
spec:
  ports:
  - name: pro-web
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    prometheus: stable-kube-prometheus-sta-prometheus
  type: LoadBalancer