apiVersion: v1
kind: Service
metadata:
  name: prometheus-nlb
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
spec:
  ports:
  - name: pro-web
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    prometheus: stable-kube-prometheus-sta-prometheus
  type: LoadBalancer