apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: pm-adapter
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: prometheus-adapter
    helm:
      values: |-
        prometheus:
          url: http://stable-kube-prometheus-sta-prometheus.monitoring.svc
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 2.13.0
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true