# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-gateway
#   namespace: application
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       application: api-gateway
#   template:
#     metadata:
#       labels:
#         application: api-gateway
#     spec:
#       nodeSelector:
#         eks.amazonaws.com/nodegroup: apigateway_node_group
#       containers:
#       - name: api-gateway
#         image: 916657902198.dkr.ecr.us-east-2.amazonaws.com/api_gateway:22
#         resources:
#           requests:
#             cpu: 1000m
#             # memory: 0.8Gi
#             memory: 1000Mi
#         env:
#           - name: layout_analysis_url
#             value: http://layout-analysis.application.svc:8081
#           - name: character_detection_url
#             value: http://character-detection.application.svc:8081
#           - name: character_recognition_url
#             value: http://character-recognition.application.svc:8081
#           - name: image_embedding_url
#             value: http://image-embedding.application.svc:8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: application
spec:
  replicas: 2
  selector:
    matchLabels:
      application: api-gateway
  template:
    metadata:
      labels:
        application: api-gateway
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: apigateway_node_group
      containers:
      - name: api-gateway
        image: 916657902198.dkr.ecr.us-east-2.amazonaws.com/api_gateway:24
        resources:
          requests:
            cpu: 1000m
            # memory: 0.8Gi
            memory: 1000Mi
        env:
          - name: redis_host
            value: redis-master.messagesys.svc
          - name: rabbitmq_host
            value: production-rabbitmqcluster.messagesys.svc

---
kind: Service
apiVersion: v1
metadata:
  name: api-gateway
  namespace: application
  labels:
    application: api-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0b5cf4d15494bb9cf,eipalloc-0d220274b39d629d1"
    ## cross zone load 옵션을 줘야 각 ip에 고루 분산됨
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  type: LoadBalancer
  selector:
    application: api-gateway
  ports:
  - name: html
    port: 80
    targetPort: 80
