---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app-1
  template:
    metadata:
      labels:
        app: example-app-1
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    svc: example-app
spec:
  selector:
    app: example-app-1
  ports:
  - name: web
    port: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    prometheus: devops
spec:
  selector:
    matchLabels:
      ## 파드 레이블 일치
      app: example-app-1
  endpoints:
  - port: web