telemetry:
  enabled: true
global:
  istioNamespace: istio-system
meshConfig:
  ingressService: istio-gateway
  ingressSelector: gateway
pilot:
  nodeSelector:
    eks.amazonaws.com/nodegroup: admin_node_group